config/routes.rb
Rails.application.routes.draw do
  resources :degree_plans, only: [:show, :index], constraints: {format: 'json'}

end

app/models/degree_plan.rb
class DegreePlan < ActiveRecord::Base
  extend FriendlyId
  friendly_id :sluggified_url, use: :slugged
  serialize :plan, JSON

  validates :name, presence: true, uniqueness: {scope: [:degree_type, :degree_awarded]}
  validates :degree_type, presence: true
  validates :degree_awarded, presence: true
  validates :slug, presence: true, uniqueness: true

  def sluggified_url
    "#{name} #{degree_awarded} #{degree_type}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_filter :set_default_response_format

  private
  def set_default_response_format
    request.format = :json
  end

end

app/controllers/degree_plans_controller.rb
class DegreePlansController < ApplicationController
  before_action :set_degree_plan, only: [:show, :edit, :update, :destroy]

  # GET /degree_plans
  # GET /degree_plans.json
  def index
    @degree_plans = DegreePlan.all
  end

  # GET /degree_plans/1
  # GET /degree_plans/1.json
  def show
  end

  # GET /degree_plans/new
  def new
    @degree_plan = DegreePlan.new
  end

  # GET /degree_plans/1/edit
  def edit
  end

  # POST /degree_plans
  # POST /degree_plans.json
  def create
    @degree_plan = DegreePlan.new(degree_plan_params)

    respond_to do |format|
      if @degree_plan.save
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully created.' }
        format.json { render :show, status: :created, location: @degree_plan }
      else
        format.html { render :new }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degree_plans/1
  # PATCH/PUT /degree_plans/1.json
  def update
    respond_to do |format|
      if @degree_plan.update(degree_plan_params)
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree_plan }
      else
        format.html { render :edit }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degree_plans/1
  # DELETE /degree_plans/1.json
  def destroy
    @degree_plan.destroy
    respond_to do |format|
      format.html { redirect_to degree_plans_url, notice: 'Degree plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree_plan
      @degree_plan = DegreePlan.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_plan_params
      params.require(:degree_plan).permit(:name, :degree_type, :degree_awarded, :plan)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degree_plans_helper.rb
module DegreePlansHelper
end

app/views/degree_plans/_form.html.erb
<%= form_for(@degree_plan) do |f| %>
  <% if @degree_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree_plan.errors.count, "error") %> prohibited this degree_plan from being saved:</h2>

      <ul>
      <% @degree_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :degree_type %><br>
    <%= f.text_field :degree_type %>
  </div>
  <div class="field">
    <%= f.label :degree_awarded %><br>
    <%= f.text_field :degree_awarded %>
  </div>
  <div class="field">
    <%= f.label :plan %><br>
    <%= f.text_area :plan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degree_plans/edit.html.erb
<h1>Editing Degree Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree_plan %> |
<%= link_to 'Back', degree_plans_path %>

app/views/degree_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Degree Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Degree type</th>
      <th>Degree awarded</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degree_plans.each do |degree_plan| %>
      <tr>
        <td><%= degree_plan.name %></td>
        <td><%= degree_plan.degree_type %></td>
        <td><%= degree_plan.degree_awarded %></td>
        <td><%= degree_plan.plan %></td>
        <td><%= link_to 'Show', degree_plan %></td>
        <td><%= link_to 'Edit', edit_degree_plan_path(degree_plan) %></td>
        <td><%= link_to 'Destroy', degree_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree plan', new_degree_plan_path %>

app/views/degree_plans/new.html.erb
<h1>New Degree Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', degree_plans_path %>

app/views/degree_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @degree_plan.name %>
</p>

<p>
  <strong>Degree type:</strong>
  <%= @degree_plan.degree_type %>
</p>

<p>
  <strong>Degree awarded:</strong>
  <%= @degree_plan.degree_awarded %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @degree_plan.plan %>
</p>

<%= link_to 'Edit', edit_degree_plan_path(@degree_plan) %> |
<%= link_to 'Back', degree_plans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnmDegreePlanStub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>